# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:51
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_buku', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(blank=True, choices=[('tersedia', 'Tersedia'), ('dipinjam', 'Dipinjam')], default='tersedia', max_length=15, verbose_name='Status Buku')),
                ('kondisi', models.CharField(blank=True, choices=[('baik', 'Baik'), ('rusak', 'Rusak'), ('hilang', 'Hilang')], default='baik', max_length=15, verbose_name='Kondisi Buku')),
            ],
            options={
                'verbose_name_plural': 'Buku',
            },
        ),
        migrations.CreateModel(
            name='Detail_Sirkulasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_buku', to='perpusApp.Buku')),
            ],
            options={
                'verbose_name_plural': 'Detail_Sirkulasi',
            },
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15, unique=True)),
                ('jdl_buku', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('thn_terbit', models.CharField(max_length=4, null=True)),
                ('foto_sampul', models.ImageField(blank=True, null=True, upload_to='statis/image_katalog')),
            ],
            options={
                'verbose_name_plural': 'Katalog',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerbit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Penerbit',
            },
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penulis', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Penulis',
            },
        ),
        migrations.CreateModel(
            name='Rak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_rak', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Rak',
            },
        ),
        migrations.CreateModel(
            name='Sirkulasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_sirkulasi', models.CharField(max_length=10, unique=True)),
                ('tgl_pesan', models.DateField(blank=True, null=True)),
                ('tgl_pinjam', models.DateField(blank=True, null=True)),
                ('tgl_kembali', models.DateField(blank=True, null=True)),
                ('lama_pinjam', models.IntegerField(blank=True, null=True)),
                ('jumlah_pinjam', models.IntegerField(null=True)),
                ('denda', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('anggota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anggota_sirkulasi', to='userApp.Anggota')),
                ('petugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petugas_sirkulasi', to='userApp.Petugas')),
            ],
            options={
                'verbose_name_plural': 'Sirkulasi',
            },
        ),
        migrations.AddField(
            model_name='katalog',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategori_katalog', to='perpusApp.Kategori'),
        ),
        migrations.AddField(
            model_name='katalog',
            name='penerbit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penerbit_katalog', to='perpusApp.Penerbit'),
        ),
        migrations.AddField(
            model_name='katalog',
            name='penulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penulis_katalog', to='perpusApp.Penulis'),
        ),
        migrations.AddField(
            model_name='katalog',
            name='rak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rak_katalog', to='perpusApp.Rak'),
        ),
        migrations.AddField(
            model_name='detail_sirkulasi',
            name='sirkulasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sirkulasi_detail', to='perpusApp.Sirkulasi'),
        ),
        migrations.AddField(
            model_name='buku',
            name='katalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buku_katalog', to='perpusApp.Katalog'),
        ),
    ]
