# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_sirkulasi',
            name='buku',
        ),
        migrations.RemoveField(
            model_name='detail_sirkulasi',
            name='sirkulasi',
        ),
        migrations.AddField(
            model_name='sirkulasi',
            name='buku',
            field=models.ManyToManyField(to='perpusApp.Buku'),
        ),
        migrations.AlterField(
            model_name='sirkulasi',
            name='status',
            field=models.CharField(blank=True, choices=[('pesan', 'Dipesan'), ('pinjam', 'Dipinjam'), ('kembali', 'Kembali'), ('telat', 'Telat')], max_length=20, null=True, verbose_name='Status Sirkulasi'),
        ),
        migrations.DeleteModel(
            name='Detail_Sirkulasi',
        ),
    ]
