# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0005_auto_20171210_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='isbn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
