# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0006_auto_20171211_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kd_itemBuku',
            new_name='kd_buku',
        ),
    ]
