# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0007_auto_20171211_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kd_buku',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Kode Buku'),
        ),
    ]
