# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0008_auto_20171211_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buku',
            old_name='kd_buku',
            new_name='kd_itemBuku',
        ),
    ]
