# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0009_auto_20171212_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kondisi',
            field=models.CharField(blank=True, choices=[('Baik', 'Baik'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang')], default='baik', max_length=15, verbose_name='Kondisi Buku'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='status',
            field=models.CharField(blank=True, choices=[('Tersedia', 'Tersedia'), ('Dipinjam', 'Dipinjam')], default='tersedia', max_length=15, verbose_name='Status Buku'),
        ),
        migrations.AlterField(
            model_name='sirkulasi',
            name='status',
            field=models.CharField(blank=True, choices=[('Dipesan', 'Dipesan'), ('Dipinjam', 'Dipinjam'), ('Kembali', 'Kembali'), ('Telat', 'Telat')], max_length=20, null=True, verbose_name='Status Sirkulasi'),
        ),
    ]
