# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0012_auto_20171223_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasi',
            name='buku',
            field=models.ManyToManyField(related_name='buku_sirkulasi', to='perpusApp.Buku'),
        ),
    ]
