# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0013_auto_20171223_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasi',
            name='buku',
            field=models.ManyToManyField(blank=True, related_name='buku_sirkulasi', to='perpusApp.Buku'),
        ),
        migrations.AlterField(
            model_name='sirkulasi',
            name='jumlah_pinjam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sirkulasi',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petugas_sirkulasi', to='userApp.Petugas'),
        ),
    ]
