# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpusApp', '0014_auto_20171229_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='kondisi',
            field=models.CharField(blank=True, choices=[('Baik', 'Baik'), ('Rusak', 'Rusak'), ('Hilang', 'Hilang')], default='Baik', max_length=15, verbose_name='Kondisi Buku'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='status',
            field=models.CharField(blank=True, choices=[('Tersedia', 'Tersedia'), ('Dipinjam', 'Dipinjam')], default='Tersedia', max_length=15, verbose_name='Status Buku'),
        ),
    ]
