# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jk', models.CharField(blank=True, choices=[('laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], default='laki', max_length=15, null=True, verbose_name='Jenis Kelamin')),
                ('agama', models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen', 'Kristen'), ('katholik', 'Katholik'), ('hindu', 'Hindu'), ('budha', 'Budha'), ('other', 'Other')], default='islam', max_length=20, null=True, verbose_name='Agama')),
                ('alamat', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='statis/image_anggota')),
                ('user_id', models.CharField(max_length=15)),
                ('pass_id', models.CharField(max_length=15)),
                ('ttl', models.DateField(blank=True, max_length=8, null=True, verbose_name='Tanggal Lahir')),
                ('status', models.CharField(blank=True, choices=[('0', 'Tidak Aktif'), ('1', 'Aktif')], default='1', max_length=15, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Anggota',
            },
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_petugas', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(max_length=20)),
                ('pass_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('jk', models.CharField(blank=True, choices=[('laki', 'Laki-Laki'), ('perempuan', 'Perempuan')], default='laki', max_length=20, null=True, verbose_name='Jenis Kelamin')),
                ('alamat', models.TextField(blank=True, null=True)),
                ('ttl', models.DateField(blank=True, max_length=8, null=True, verbose_name='tanggal Lahir')),
                ('agama', models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen', 'Kristen'), ('katholik', 'Katholik'), ('hindu', 'Hindu'), ('budha', 'Budha'), ('other', 'Other')], default='islam', max_length=20, null=True, verbose_name='Agama')),
            ],
            options={
                'verbose_name_plural': 'Petugas',
            },
        ),
    ]
