# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20171121_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggota',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='petugas',
            old_name='user_id',
            new_name='user',
        ),
    ]
